/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package uscivicsstudy;

import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.SwingUtilities;

/**
 *
 * @author ThienDinh
 */
public class FrameDictionary extends javax.swing.JFrame {

    public static boolean hideAbleForm;
    private WordDefinition searchEngine;
    private Example exampleEngine;
    private int history;
    private String definition;
    private String example;
    private Dimension defaultDimension;
    private Thread audioThread;
    private int countAudio;
    private Vdict vnDict;

    /**
     * Creates new form SearchForm
     */
    public FrameDictionary() {
        hideAbleForm = true;
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameDictionary.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        initComponents();
        searchEngine = new WordDefinition();
        exampleEngine = new Example();
        Dimension screen = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(screen.width / 2 - this.getWidth() / 2,
                screen.height / 2 - this.getHeight() / 2);
        defaultDimension = this.getSize();
        this.btnGroupLang.add(this.btnRadEngEng);
        this.btnGroupLang.add(this.btnRadEngVn);
        this.btnRead.setEnabled(false);
        this.btnTgDiEx.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupLang = new javax.swing.ButtonGroup();
        pnlBackground = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDefinition = new javax.swing.JTextArea();
        btnRead = new javax.swing.JButton();
        txtWord = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lbWord0 = new javax.swing.JLabel();
        lbWord1 = new javax.swing.JLabel();
        lbWord2 = new javax.swing.JLabel();
        lbWord3 = new javax.swing.JLabel();
        lbWord4 = new javax.swing.JLabel();
        lbWord5 = new javax.swing.JLabel();
        lbWord6 = new javax.swing.JLabel();
        lbWord7 = new javax.swing.JLabel();
        lbWord8 = new javax.swing.JLabel();
        btnTgDiEx = new javax.swing.JToggleButton();
        lbPowered = new javax.swing.JLabel();
        btnRadEngEng = new javax.swing.JRadioButton();
        btnRadEngVn = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dictionary");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                formWindowLostFocus(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        txaDefinition.setEditable(false);
        txaDefinition.setBackground(new java.awt.Color(255, 255, 217));
        txaDefinition.setColumns(20);
        txaDefinition.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txaDefinition.setLineWrap(true);
        txaDefinition.setRows(5);
        txaDefinition.setToolTipText("Right click to copy");
        txaDefinition.setWrapStyleWord(true);
        txaDefinition.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txaDefinition.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txaDefinition.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txaDefinitionMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(txaDefinition);

        btnRead.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnRead.setText("Read");
        btnRead.setToolTipText("Listen to the word's pronunciation.");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        txtWord.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtWord.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtWord.setToolTipText("Right click to paste.");
        txtWord.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtWord.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtWordCaretUpdate(evt);
            }
        });
        txtWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtWordMouseClicked(evt);
            }
        });
        txtWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWordActionPerformed(evt);
            }
        });
        txtWord.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtWordFocusGained(evt);
            }
        });
        txtWord.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtWordInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txtWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtWordKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtWordKeyTyped(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setToolTipText("Look up definition.");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jPanel1.setLayout(new java.awt.GridLayout(3, 3));

        lbWord0.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbWord0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWord0.setToolTipText("Right click.");
        lbWord0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbWord0MouseClicked(evt);
            }
        });
        jPanel1.add(lbWord0);

        lbWord1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbWord1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWord1.setToolTipText("Right click.");
        lbWord1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbWord1MouseClicked(evt);
            }
        });
        jPanel1.add(lbWord1);

        lbWord2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbWord2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWord2.setToolTipText("Right click.");
        lbWord2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbWord2MouseClicked(evt);
            }
        });
        jPanel1.add(lbWord2);

        lbWord3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbWord3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWord3.setToolTipText("Right click.");
        lbWord3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbWord3MouseClicked(evt);
            }
        });
        jPanel1.add(lbWord3);

        lbWord4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbWord4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWord4.setToolTipText("Right click.");
        lbWord4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbWord4MouseClicked(evt);
            }
        });
        jPanel1.add(lbWord4);

        lbWord5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbWord5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWord5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbWord5MouseClicked(evt);
            }
        });
        jPanel1.add(lbWord5);

        lbWord6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbWord6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWord6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbWord6MouseClicked(evt);
            }
        });
        jPanel1.add(lbWord6);

        lbWord7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbWord7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWord7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbWord7MouseClicked(evt);
            }
        });
        jPanel1.add(lbWord7);

        lbWord8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lbWord8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbWord8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbWord8MouseClicked(evt);
            }
        });
        jPanel1.add(lbWord8);

        btnTgDiEx.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnTgDiEx.setText("Show Example");
        btnTgDiEx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTgDiExActionPerformed(evt);
            }
        });

        lbPowered.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        lbPowered.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPowered.setText("∞ Powered by Ahdictionary.com and Dictionary.com ∞ ");
        lbPowered.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbPoweredMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbPoweredMouseExited(evt);
            }
        });

        btnRadEngEng.setSelected(true);
        btnRadEngEng.setText("English - English");
        btnRadEngEng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadEngEngActionPerformed(evt);
            }
        });

        btnRadEngVn.setText("English - Vietnamese");
        btnRadEngVn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRadEngVnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbPowered, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnRadEngEng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnRadEngVn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                        .addComponent(btnTgDiEx, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnRead, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtWord, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRadEngVn)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGap(0, 29, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbPowered)
                        .addGap(7, 7, 7))
                    .addGroup(pnlBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRadEngEng)
                            .addComponent(btnTgDiEx)
                            .addComponent(btnRead, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String text = this.txtWord.getText().toLowerCase().trim();
        this.txtWord.setText(text);
        if (!text.equals("")) {
            vnDict = new Vdict();
            vnDict.setWord(text);
            searchEngine.setWord(text);
            if (this.btnRadEngVn.isSelected()) {
                definition = vnDict.getDefinition();
                this.txaDefinition.setText(definition);
                this.btnRead.setEnabled(true);
            } else {
                definition = searchEngine.getDefinition();
                this.txaDefinition.setText(definition);
                exampleEngine.setWord(text);
                example = exampleEngine.findExample();
                this.btnTgDiEx.setSelected(false);
                this.btnTgDiEx.setText("Show Example");
                this.btnRead.setEnabled(true);
                this.btnTgDiEx.setEnabled(true);
            }
        } else {
            this.txaDefinition.setText("Please input a word for searching!");
        }

        if (this.txaDefinition.getText().equals("")) {
            this.txaDefinition.setText("The program couldn't find \"" + this.txtWord.getText() + "\" in the dictionary!");
            this.txtWord.setText(this.txtWord.getText().trim());
            this.btnRead.setEnabled(false);
            this.btnTgDiEx.setEnabled(false);
        } else if (!this.txtWord.getText().equals("")
                && !this.lbWord0.getText().equals(this.txtWord.getText())
                && !this.lbWord1.getText().equals(this.txtWord.getText())
                && !this.lbWord2.getText().equals(this.txtWord.getText())
                && !this.lbWord3.getText().equals(this.txtWord.getText())
                && !this.lbWord4.getText().equals(this.txtWord.getText())
                && !this.lbWord5.getText().equals(this.txtWord.getText())
                && !this.lbWord6.getText().equals(this.txtWord.getText())
                && !this.lbWord7.getText().equals(this.txtWord.getText())
                && !this.lbWord8.getText().equals(this.txtWord.getText())) {
            switch (this.history) {
                case 0:
                    this.lbWord0.setText(this.txtWord.getText());
                    this.history++;
                    break;
                case 1:
                    this.lbWord1.setText(this.txtWord.getText());
                    this.history++;
                    break;
                case 2:
                    this.lbWord2.setText(this.txtWord.getText());
                    this.history++;
                    break;
                case 3:
                    this.lbWord3.setText(this.txtWord.getText());
                    this.history++;
                    break;
                case 4:
                    this.lbWord4.setText(this.txtWord.getText());
                    this.history++;
                    break;
                case 5:
                    this.lbWord5.setText(this.txtWord.getText());
                    this.history++;
                    break;
                case 6:
                    this.lbWord6.setText(this.txtWord.getText());
                    this.history++;
                    break;
                case 7:
                    this.lbWord7.setText(this.txtWord.getText());
                    this.history++;
                    break;
                case 8:
                    this.lbWord8.setText(this.txtWord.getText());
                    this.history -= 8;
                    break;
            }
        }
        this.btnSearch.setEnabled(false);

    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWordActionPerformed
        // TODO add your handling code here:
        this.btnSearch.doClick();
    }//GEN-LAST:event_txtWordActionPerformed

    private void txtWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtWordMouseClicked
        // TODO add your handling code here:
        if (SwingUtilities.isRightMouseButton(evt)) {
            try {
                String text = String.valueOf(java.awt.Toolkit.getDefaultToolkit()
                        .getSystemClipboard().getData(DataFlavor.stringFlavor));
                this.txtWord.setText(text);
            } catch (UnsupportedFlavorException ex) {
            } catch (IOException ex) {
            }
        }
    }//GEN-LAST:event_txtWordMouseClicked

    private void formWindowLostFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowLostFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowLostFocus

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        // TODO add your handling code here:  
        try {
            if (audioThread != null) {
                audioThread.interrupt();
            }
            Audio pronounce = new Audio();
            URL audio = new URL("http://www.ahdictionary.com/application/resources/wavs/"
                    + this.searchEngine.getPronunciation() + ".wav");
            pronounce.setVoiceLink(audio);
            audioThread = new Thread(pronounce, "Pronunciation" + (this.countAudio++));
            audioThread.start();
        } catch (MalformedURLException ex) {
            System.out.println("== URL error!!");
        }

    }//GEN-LAST:event_btnReadActionPerformed

    private void txaDefinitionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txaDefinitionMouseClicked
        // TODO add your handling code here:
        if (SwingUtilities.isRightMouseButton(evt)) {
            StringSelection stringSelection = new StringSelection(this.txaDefinition.getSelectedText());
            Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
            clipboard.setContents(stringSelection, stringSelection);
        }
    }//GEN-LAST:event_txaDefinitionMouseClicked

    private void lbWord0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWord0MouseClicked
        // TODO add your handling code here:
        if (SwingUtilities.isRightMouseButton(evt)) {
            String text = this.lbWord0.getText();
            this.txtWord.setText(text);
            this.btnSearch.setEnabled(true);
        }
    }//GEN-LAST:event_lbWord0MouseClicked

    private void lbWord1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWord1MouseClicked
        // TODO add your handling code here:
        if (SwingUtilities.isRightMouseButton(evt)) {
            String text = this.lbWord1.getText();
            this.txtWord.setText(text);
            this.btnSearch.setEnabled(true);
        }
    }//GEN-LAST:event_lbWord1MouseClicked

    private void lbWord2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWord2MouseClicked
        // TODO add your handling code here:
        if (SwingUtilities.isRightMouseButton(evt)) {
            String text = this.lbWord2.getText();
            this.txtWord.setText(text);
            this.btnSearch.setEnabled(true);
        }
    }//GEN-LAST:event_lbWord2MouseClicked

    private void lbWord3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWord3MouseClicked
        // TODO add your handling code here:
        if (SwingUtilities.isRightMouseButton(evt)) {
            String text = this.lbWord3.getText();
            this.txtWord.setText(text);
            this.btnSearch.setEnabled(true);
        }
    }//GEN-LAST:event_lbWord3MouseClicked

    private void lbWord4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWord4MouseClicked
        // TODO add your handling code here:
        if (SwingUtilities.isRightMouseButton(evt)) {
            String text = this.lbWord4.getText();
            this.txtWord.setText(text);
            this.btnSearch.setEnabled(true);
        }
    }//GEN-LAST:event_lbWord4MouseClicked

    private void txtWordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtWordFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWordFocusGained

    private void txtWordInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtWordInputMethodTextChanged
        // TODO add your handling code here: 
    }//GEN-LAST:event_txtWordInputMethodTextChanged

    private void txtWordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWordKeyTyped
        // TODO add your handling code here:  
    }//GEN-LAST:event_txtWordKeyTyped

    private void txtWordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtWordKeyReleased
        // TODO add your handling code here:         
    }//GEN-LAST:event_txtWordKeyReleased

    private void txtWordCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtWordCaretUpdate
        // TODO add your handling code here:                     
        this.btnSearch.setEnabled(true);
    }//GEN-LAST:event_txtWordCaretUpdate

    private void btnTgDiExActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTgDiExActionPerformed
        // TODO add your handling code here:
        if (this.btnTgDiEx.isSelected()) {
            if (example.equals("")) {
                this.txaDefinition.setText("Sorry! The program couldn't find any example!");
            } else {
                this.txaDefinition.setText(example);
            }
            this.btnTgDiEx.setText("Back to Definition");
        } else {
            this.txaDefinition.setText(definition);
            this.btnTgDiEx.setText("Show Example");
        }
    }//GEN-LAST:event_btnTgDiExActionPerformed

    private void lbPoweredMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPoweredMouseEntered
        // TODO add your handling code here:
        Font font = new Font("Segoe UI", Font.ITALIC, 10);
        this.lbPowered.setFont(font);
    }//GEN-LAST:event_lbPoweredMouseEntered

    private void lbPoweredMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbPoweredMouseExited
        // TODO add your handling code here:
        Font font = new Font("Segoe UI", Font.BOLD, 10);
        this.lbPowered.setFont(font);
    }//GEN-LAST:event_lbPoweredMouseExited

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        try {
            this.audioThread.interrupt();
        } catch (Exception ex) {
            System.out.println("formWindowClosing: " + ex.getMessage());
        }
    }//GEN-LAST:event_formWindowClosing

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void lbWord5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWord5MouseClicked
        // TODO add your handling code here:
        if (SwingUtilities.isRightMouseButton(evt)) {
            String text = this.lbWord5.getText();
            this.txtWord.setText(text);
            this.btnSearch.setEnabled(true);
        }
    }//GEN-LAST:event_lbWord5MouseClicked

    private void lbWord6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWord6MouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            String text = this.lbWord6.getText();
            this.txtWord.setText(text);
            this.btnSearch.setEnabled(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_lbWord6MouseClicked

    private void lbWord7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWord7MouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            String text = this.lbWord7.getText();
            this.txtWord.setText(text);
            this.btnSearch.setEnabled(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_lbWord7MouseClicked

    private void lbWord8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbWord8MouseClicked
        if (SwingUtilities.isRightMouseButton(evt)) {
            String text = this.lbWord8.getText();
            this.txtWord.setText(text);
            this.btnSearch.setEnabled(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_lbWord8MouseClicked

    private void btnRadEngEngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadEngEngActionPerformed
        // TODO add your handling code here:
            this.lbPowered.setText("∞ Powered by Ahdictionary.com and Dictionary.com ∞ ");
    }//GEN-LAST:event_btnRadEngEngActionPerformed

    private void btnRadEngVnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRadEngVnActionPerformed
        // TODO add your handling code here:        
            this.lbPowered.setText("∞ Powered by Vdict.com ∞ ");
    }//GEN-LAST:event_btnRadEngVnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroupLang;
    private javax.swing.JRadioButton btnRadEngEng;
    private javax.swing.JRadioButton btnRadEngVn;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnSearch;
    private javax.swing.JToggleButton btnTgDiEx;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbPowered;
    private javax.swing.JLabel lbWord0;
    private javax.swing.JLabel lbWord1;
    private javax.swing.JLabel lbWord2;
    private javax.swing.JLabel lbWord3;
    private javax.swing.JLabel lbWord4;
    private javax.swing.JLabel lbWord5;
    private javax.swing.JLabel lbWord6;
    private javax.swing.JLabel lbWord7;
    private javax.swing.JLabel lbWord8;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JTextArea txaDefinition;
    private javax.swing.JTextField txtWord;
    // End of variables declaration//GEN-END:variables
}
